//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoWorkArgs", Namespace="http://schemas.datacontract.org/2004/07/D3K.Diagnostics.Log4net.Demo.Wcf.Server")]
    [System.SerializableAttribute()]
    public partial class DoWorkArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Arg1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Arg2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Arg1 {
            get {
                return this.Arg1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Arg1Field, value) != true)) {
                    this.Arg1Field = value;
                    this.RaisePropertyChanged("Arg1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Arg2 {
            get {
                return this.Arg2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Arg2Field, value) != true)) {
                    this.Arg2Field = value;
                    this.RaisePropertyChanged("Arg2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoWorkResult", Namespace="http://schemas.datacontract.org/2004/07/D3K.Diagnostics.Log4net.Demo.Wcf.Server")]
    [System.SerializableAttribute()]
    public partial class DoWorkResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DoWork", ReplyAction="http://tempuri.org/IService/DoWorkResponse")]
        D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.DoWorkResult DoWork(D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.DoWorkArgs args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DoWork", ReplyAction="http://tempuri.org/IService/DoWorkResponse")]
        System.Threading.Tasks.Task<D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.DoWorkResult> DoWorkAsync(D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.DoWorkArgs args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.IService>, D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.DoWorkResult DoWork(D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.DoWorkArgs args) {
            return base.Channel.DoWork(args);
        }
        
        public System.Threading.Tasks.Task<D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.DoWorkResult> DoWorkAsync(D3K.Diagnostics.Log4net.Demo.Wcf.Client.ServiceReference.DoWorkArgs args) {
            return base.Channel.DoWorkAsync(args);
        }
    }
}
